apiVersion: v2
name: frontend
description: Frontend React application chart
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: amex-library
    version: 0.1.0
    repository: file://../amex-library

