nameOverride: backend
image:
  repository: us-central1-docker.pkg.dev/demo-project/app-images/backend
  tag: prod-approved
replicaCount: 3
service:
  port: 8000
ingress:
  enabled: true
  host: backend.example.com
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi
env:
  APP_ENV: prod
  MONGODB_URI_SECRET: mongodb-uri
  TEMPORAL_HOST: temporal-frontend.platform-prod.svc.cluster.local:7233

