nameOverride: backend
image:
  repository: us-central1-docker.pkg.dev/demo-project/app-images/backend
  tag: test-approved
replicaCount: 2
service:
  port: 8000
ingress:
  enabled: true
  host: backend-test.example.com
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
env:
  APP_ENV: test
  MONGODB_URI_SECRET: mongodb-uri
  TEMPORAL_HOST: temporal-frontend.platform-test.svc.cluster.local:7233

