fullnameOverride: mongodb
auth:
  enabled: true
architecture: standalone
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  size: 5Gi

