fullnameOverride: mongodb
auth:
  enabled: true
architecture: standalone
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
persistence:
  enabled: true
  size: 10Gi

