apiVersion: v2
name: agent
description: Agent orchestrator service for the Insights platform
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: amex-library
    version: 0.1.0
    repository: "file://../../../charts/amex-library"
