apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: frontend
            path: apps/frontend
            namespace: frontend-prod
          - name: backend
            path: apps/backend
            namespace: backend-prod
          - name: agents
            path: apps/agents
            namespace: agents-prod
          - name: mongodb
            path: platform/mongodb
            namespace: platform-prod
          - name: temporal
            path: platform/temporal
            namespace: platform-prod
          - name: langfuse
            path: platform/langfuse
            namespace: platform-prod
  template:
    metadata:
      name: 'prod-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sandeeprayala/gke-gitops-platform-demo.git
        targetRevision: feature/gitops-argocd-helm-restructure
        path: '{{path}}'
        helm:
          valueFiles:
            - envs/prod-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

