apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: frontend
            path: apps/frontend
            namespace: frontend-test
          - name: backend
            path: apps/backend
            namespace: backend-test
          - name: agents
            path: apps/agents
            namespace: agents-test
          - name: mongodb
            path: platform/mongodb
            namespace: platform-test
          - name: temporal
            path: platform/temporal
            namespace: platform-test
          - name: langfuse
            path: platform/langfuse
            namespace: platform-test
  template:
    metadata:
      name: 'test-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sandeeprayala/gke-gitops-platform-demo.git
        targetRevision: feature/gitops-argocd-helm-restructure
        path: '{{path}}'
        helm:
          valueFiles:
            - envs/test-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

