nameOverride: frontend
image:
  repository: us-central1-docker.pkg.dev/demo-project/app-images/frontend
  tag: prod-approved
replicaCount: 3
service:
  port: 80
ingress:
  enabled: true
  host: frontend.example.com
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
env:
  APP_ENV: prod

