environment: test
replicaCount: 2
image:
  digest: sha256:TEST_FRONTEND_IMAGE_DIGEST
ingress:
  enabled: true
  host: frontend.test.example.com
  annotations: {}
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
