nameOverride: frontend
image:
  repository: us-central1-docker.pkg.dev/demo-project/app-images/frontend
  tag: test-approved
replicaCount: 2
service:
  port: 80
ingress:
  enabled: true
  host: frontend-test.example.com
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  APP_ENV: test

